---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
- type: document
  path: views/words.md
  label: Words
  match: "**/*"
- type: document
  path: index.md
  label: About
  match: "**/*"
- type: document
  path: views/contact.md
  label: Contact
  match: "**/*"
- type: directory
  path: _press
  label: Press
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Settings
  create: all
  match: "*.yml"
  new_doc_ext: yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
