---
label: Project
hide_body: true
display_field: institution
fields:
- type: text
  name: type
  label: type
- type: text
  name: role
  label: role
- type: text
  name: institution
  label: institution
- type: text
  name: start_date
  label: start_date
- type: text
  name: end_date
  label: end_date
- type: textarea
  name: description
  label: description
- type: file
  name: image_url
  label: image_url
